/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OntologyRouteImport } from './routes/ontology'
import { Route as KnowledgePlatformRouteImport } from './routes/knowledge-platform'
import { Route as EngineeringStandardsRouteImport } from './routes/engineering-standards'
import { Route as DeveloperPlatformRouteImport } from './routes/developer-platform'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AiPlatformRouteImport } from './routes/ai-platform'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OntologyRoute = OntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgePlatformRoute = KnowledgePlatformRouteImport.update({
  id: '/knowledge-platform',
  path: '/knowledge-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringStandardsRoute = EngineeringStandardsRouteImport.update({
  id: '/engineering-standards',
  path: '/engineering-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPlatformRoute = DeveloperPlatformRouteImport.update({
  id: '/developer-platform',
  path: '/developer-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlatformRoute = AiPlatformRouteImport.update({
  id: '/ai-platform',
  path: '/ai-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-platform': typeof AiPlatformRoute
  '/architecture': typeof ArchitectureRoute
  '/developer-platform': typeof DeveloperPlatformRoute
  '/engineering-standards': typeof EngineeringStandardsRoute
  '/knowledge-platform': typeof KnowledgePlatformRoute
  '/ontology': typeof OntologyRoute
  '/packages': typeof PackagesRoute
  '/templates': typeof TemplatesRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-platform': typeof AiPlatformRoute
  '/architecture': typeof ArchitectureRoute
  '/developer-platform': typeof DeveloperPlatformRoute
  '/engineering-standards': typeof EngineeringStandardsRoute
  '/knowledge-platform': typeof KnowledgePlatformRoute
  '/ontology': typeof OntologyRoute
  '/packages': typeof PackagesRoute
  '/templates': typeof TemplatesRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities': typeof CapabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-platform': typeof AiPlatformRoute
  '/architecture': typeof ArchitectureRoute
  '/developer-platform': typeof DeveloperPlatformRoute
  '/engineering-standards': typeof EngineeringStandardsRoute
  '/knowledge-platform': typeof KnowledgePlatformRoute
  '/ontology': typeof OntologyRoute
  '/packages': typeof PackagesRoute
  '/templates': typeof TemplatesRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-platform'
    | '/architecture'
    | '/developer-platform'
    | '/engineering-standards'
    | '/knowledge-platform'
    | '/ontology'
    | '/packages'
    | '/templates'
    | '/capabilities/$slug'
    | '/capabilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-platform'
    | '/architecture'
    | '/developer-platform'
    | '/engineering-standards'
    | '/knowledge-platform'
    | '/ontology'
    | '/packages'
    | '/templates'
    | '/capabilities/$slug'
    | '/capabilities'
  id:
    | '__root__'
    | '/'
    | '/ai-platform'
    | '/architecture'
    | '/developer-platform'
    | '/engineering-standards'
    | '/knowledge-platform'
    | '/ontology'
    | '/packages'
    | '/templates'
    | '/capabilities/$slug'
    | '/capabilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPlatformRoute: typeof AiPlatformRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DeveloperPlatformRoute: typeof DeveloperPlatformRoute
  EngineeringStandardsRoute: typeof EngineeringStandardsRoute
  KnowledgePlatformRoute: typeof KnowledgePlatformRoute
  OntologyRoute: typeof OntologyRoute
  PackagesRoute: typeof PackagesRoute
  TemplatesRoute: typeof TemplatesRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontology': {
      id: '/ontology'
      path: '/ontology'
      fullPath: '/ontology'
      preLoaderRoute: typeof OntologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-platform': {
      id: '/knowledge-platform'
      path: '/knowledge-platform'
      fullPath: '/knowledge-platform'
      preLoaderRoute: typeof KnowledgePlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-standards': {
      id: '/engineering-standards'
      path: '/engineering-standards'
      fullPath: '/engineering-standards'
      preLoaderRoute: typeof EngineeringStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-platform': {
      id: '/developer-platform'
      path: '/developer-platform'
      fullPath: '/developer-platform'
      preLoaderRoute: typeof DeveloperPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-platform': {
      id: '/ai-platform'
      path: '/ai-platform'
      fullPath: '/ai-platform'
      preLoaderRoute: typeof AiPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPlatformRoute: AiPlatformRoute,
  ArchitectureRoute: ArchitectureRoute,
  DeveloperPlatformRoute: DeveloperPlatformRoute,
  EngineeringStandardsRoute: EngineeringStandardsRoute,
  KnowledgePlatformRoute: KnowledgePlatformRoute,
  OntologyRoute: OntologyRoute,
  PackagesRoute: PackagesRoute,
  TemplatesRoute: TemplatesRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
